fix typo
timescale/tsbs pull request #142
Opened 2020-12-16 07:54 UTC by SolomonAnn

Hi,

I found a typo in the filename of **pkg/targets/cassandra/bencmark.go** and I've fixed it.

Thanks

2020-12-16 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/tsbs?pullRequest=142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/tsbs?pullRequest=142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/tsbs?pullRequest=142) it.</sub>

2021-05-19 13:58 UTC, jonatas requested changes
Thanks for the update @SolomonAnn. Would you mind just keep the relevant changes and discard the comments that you made in the other parts of the code?

2021-05-25 03:07 UTC, SolomonAnn commented
@jonatas I've discarded the comments and fixed conflicts.

2021-05-26 17:51 UTC, jonatas approved these changes

2021-05-26 18:19 UTC, merged